name: Nix Flake actions

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  pull_request:
    branches: 
      - main
      - '*'
  merge_group:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write
  issues: write
  packages: write

jobs:
  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux Build (x86_64)
            os: ubuntu-latest
            system: x86_64-linux
          - name: MacOS Build (aarch64)
            os: macos-latest
            system: aarch64-darwin
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build --accept-flake-config --no-pure-eval -L ".#packages.${{ matrix.system }}.default"
