name: Update and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight, modify as needed

jobs:
  run-update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies (if required)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the update script
      - name: Run update.py
        run: python update.py

      # Step 5: Check for changes
      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || echo "Changes detected" > changes_detected.txt
        id: check_changes

      # Step 6: Create a new branch and commit changes
      - name: Commit changes
        if: success() && steps.check_changes.outputs.changes_detected
        run: |
          BRANCH_NAME="update-$(date +%Y%m%d%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Automated update by GitHub Actions"
          git push origin "$BRANCH_NAME"

      # Step 7: Notify about the new branch (optional)
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ steps.commit_changes.outputs.BRANCH_NAME }}
          title: "Automated update"
          body: "This pull request contains automated updates."
          token: ${{ secrets.GITHUB_TOKEN }}
